#%RAML 1.0 DataType
displayName: Customer
description: Describe the customer data type

type: object
properties:
  firstName:  string
  lastName: string
  address:  string
  email:  string
  number: string