#%RAML 1.0 DataType
displayName: Order
description: Describe the order data type

type: object
properties:
  poNumber: number
  signatureRequiredFlag:  boolean
  shipInstructions: string
  giftWrapFlag: boolean
  giftWrapMessage:  string
  currencyCode: string
  subTotal: number
  customerId: string